### ISSUE TITLE
komischDreh() is not a good name

### ISSUE THREAD

**Issue by flowed8** [AmirRoohi2000/RoboticsWIthArduino#1]

**Comment by AmirRoohi2000** [comment]
what name should it have, the function just shows some values and tells if there was a bumper or not, so what do you want as a name?

**Comment by flowed8** [comment]
isBumper
checkForObstacle
checkForConfusion

**Comment by AmirRoohi2000** [comment]
checkForConfusion() it is then ;)

**Comment by AmirRoohi2000** [comment]
Issue is now done 👍
